FROM python:3.7.7-slim-buster
LABEL Author lxue

ADD /wechatmi wechatmi/
WORKDIR /wechatmi

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

# CMD gunicorn -w 3 -b 0.0.0.0:8000 app:app
HEALTHCHECK CMD gunicorn -w 3 -b 0.0.0.0:8000 app:app
ENTRYPOINT gunicorn -w 3 -b 0.0.0.0:8000 app:app


